application: sudoku-app-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: sudoku.app

libraries:
- name: django
  version: "1.2"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

